# Exercises
1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [34]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
vector = tf.constant([1,2,3])
scalar = tf.constant(4)
matrix = tf.constant([[3,4],[5,6]])
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [32]:
#Find the shape, rank and size of the tensors you created in 1.
print("FOR VECTOR")
print(tf.shape(vector))
print(tf.rank(vector))
print(tf.size(vector))
print("\nFOR SCALAR")
print(tf.shape(scalar))
print(tf.rank(scalar))
print(tf.size(scalar))
print("\nFOR MATRIX")
print(tf.shape(matrix))
print(tf.rank(matrix))
print(tf.size(matrix))
print("\nFOR TENSOR")
print(tf.shape(tensor))
print(tf.rank(tensor))
print(tf.size(tensor))

FOR VECTOR
Tensor("Shape_3:0", shape=(1,), dtype=int32)
Tensor("Rank_3:0", shape=(), dtype=int32)
Tensor("Size_3:0", shape=(), dtype=int32)

FOR SCALAR
Tensor("Shape_4:0", shape=(0,), dtype=int32)
Tensor("Rank_4:0", shape=(), dtype=int32)
Tensor("Size_4:0", shape=(), dtype=int32)

FOR MATRIX
Tensor("Shape_5:0", shape=(2,), dtype=int32)
Tensor("Rank_5:0", shape=(), dtype=int32)
Tensor("Size_5:0", shape=(), dtype=int32)

FOR TENSOR
Tensor("Shape_6:0", shape=(3,), dtype=int32)
Tensor("Rank_6:0", shape=(), dtype=int32)
Tensor("Size_6:0", shape=(), dtype=int32)


In [36]:
#Create two tensors containing random values between 0 and 1 with shape [5, 300].
tensor1 = tf.random.uniform(shape=[5,300])
tensor2 = tf.random.uniform(shape=[5,300])
with tf.compat.v1.Session() as sess:
    tensor1_values = sess.run(tensor1)
    tensor2_values = sess.run(tensor2)
    print("Tensor 1:")
    print(tensor1_values)
    print("\nTensor 2:")
    print(tensor2_values)

Tensor 1:
[[0.92968595 0.15255463 0.02180505 ... 0.77000844 0.31050825 0.41351485]
 [0.3518275  0.36513293 0.2633146  ... 0.9702612  0.6071358  0.9437702 ]
 [0.30659473 0.27629066 0.35960615 ... 0.06792367 0.26620412 0.5210922 ]
 [0.7846836  0.34818387 0.12433803 ... 0.4159267  0.32896638 0.75472105]
 [0.28427684 0.45162344 0.68250775 ... 0.9435475  0.14795613 0.6498743 ]]

Tensor 2:
[[5.22193909e-01 5.40274262e-01 7.12433338e-01 ... 3.16011190e-01
  1.75500274e-01 3.63707900e-01]
 [5.76125622e-01 6.18263602e-01 5.95979929e-01 ... 6.34230733e-01
  4.36037064e-01 4.88490939e-01]
 [9.58602905e-01 6.48447037e-01 5.70000768e-01 ... 6.45319462e-01
  5.87369442e-01 6.60896301e-04]
 [7.80207753e-01 1.24651074e-01 3.14593315e-02 ... 3.27524066e-01
  3.95718813e-02 9.04308438e-01]
 [8.46472144e-01 1.82739496e-02 5.04876733e-01 ... 3.86100888e-01
  4.35885787e-01 8.41250896e-01]]


In [45]:
# 4. Multiply the two tensors using matrix multiplication.
matrix_mul = tf.matmul(tensor1, tf.transpose(tensor2))
sess = tf.compat.v1.Session()
print(sess.run(matrix_mul))

[[72.89496  76.655426 72.39402  76.32009  75.36866 ]
 [68.90211  75.47112  67.9708   76.05638  71.822716]
 [73.7473   78.918724 73.26092  80.410774 76.93975 ]
 [72.74131  76.88636  67.54693  76.307686 75.996956]
 [70.6913   73.55944  68.698746 77.62435  71.53018 ]]


In [48]:
# 5. Multiply the two tensors using dot product.
dot_product = tf.tensordot(tensor1,tf.transpose(tensor2), axes=1)
print(sess.run(dot_product))

[[77.43665  77.27891  77.246284 74.35578  70.57112 ]
 [80.482544 78.88035  79.60003  80.04146  71.783295]
 [75.4257   73.539024 74.91358  76.73252  68.46511 ]
 [78.59566  77.95484  77.86854  77.301384 71.45032 ]
 [74.25842  74.23081  75.55832  75.65319  68.13836 ]]


In [52]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor3 = tf.random.uniform(shape=[244,244,3])
print(sess.run(tensor3))

[[[0.6669375  0.7417315  0.25744712]
  [0.65871024 0.82134926 0.06344461]
  [0.83110595 0.05783844 0.11580038]
  ...
  [0.62102246 0.9217833  0.98976064]
  [0.5118464  0.98722374 0.5576005 ]
  [0.3190863  0.1005553  0.33536386]]

 [[0.7880467  0.4962448  0.9807427 ]
  [0.9264709  0.18669116 0.65439117]
  [0.56651807 0.7804693  0.60114765]
  ...
  [0.93272555 0.13287866 0.52336836]
  [0.35065544 0.6963692  0.7122097 ]
  [0.537593   0.4874848  0.43658352]]

 [[0.9837291  0.8505434  0.4439106 ]
  [0.9952302  0.98631525 0.5619955 ]
  [0.8043523  0.3436135  0.99078166]
  ...
  [0.56733596 0.10996711 0.17687297]
  [0.9219314  0.63984394 0.34871244]
  [0.09019482 0.05941415 0.33203673]]

 ...

 [[0.7166625  0.4376384  0.279482  ]
  [0.24200511 0.4345008  0.68975556]
  [0.75346637 0.5126159  0.40582228]
  ...
  [0.6247361  0.7772882  0.22834802]
  [0.18317187 0.11530447 0.2456361 ]
  [0.7836876  0.4747362  0.44893265]]

 [[0.9149116  0.7374644  0.47479415]
  [0.78600276 0.4861356  0.6264806 ]


In [53]:
# 7. Find the min and max values of the tensor.
min_value = tf.reduce_min(tensor3)
max_value = tf.reduce_max(tensor3)
print(sess.run(min_value))
print(sess.run(max_value))

2.3841858e-06
0.99999845


In [56]:
# 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor4 = tf.random.uniform(shape = [1,224,224,3])
print(sess.run(tensor4))
print("\nSqueeze")
squeeze = tf.squeeze(tensor4)
print(sess.run(tensor4))

[[[[0.745548   0.1926955  0.6854043 ]
   [0.40802717 0.07953811 0.10340726]
   [0.09365737 0.6735332  0.84683394]
   ...
   [0.22549653 0.3439381  0.7640344 ]
   [0.00637114 0.3717525  0.06117809]
   [0.31915843 0.73154163 0.9674219 ]]

  [[0.17775393 0.4599533  0.58416855]
   [0.18931472 0.18291152 0.61862123]
   [0.4537629  0.24352646 0.30007243]
   ...
   [0.6370473  0.40723634 0.24254298]
   [0.31661654 0.7923026  0.6010246 ]
   [0.77779305 0.47727394 0.3668965 ]]

  [[0.25677347 0.2700876  0.95980597]
   [0.16662979 0.1034658  0.30582452]
   [0.2357173  0.8563945  0.21818769]
   ...
   [0.06393516 0.34588492 0.89749753]
   [0.47949827 0.8710735  0.64126825]
   [0.4007858  0.19291532 0.6932992 ]]

  ...

  [[0.42601407 0.13480687 0.28502   ]
   [0.30992568 0.09366143 0.81607103]
   [0.14976549 0.32131636 0.64516675]
   ...
   [0.18937218 0.41222537 0.44618666]
   [0.16352975 0.2075789  0.94438815]
   [0.6332884  0.61966896 0.5709053 ]]

  [[0.02663684 0.5738925  0.52660763]
   [0.7

In [57]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor5 = tf.constant([2,3,4,23,43,11,23,8,19,10])
max_index = tf.argmax(tensor5)
print(sess.run(max_index))

4


In [58]:
#10. One-hot encode the tensor you created in 9.
one_hot_encoded = tf.one_hot(indices=max_index, depth=tf.size(tensor5))
with tf.compat.v1.Session() as sess:
    max_index_value = sess.run(max_index)
    print("Index of Maximum Value:", max_index_value)
    one_hot_encoded_value = sess.run(one_hot_encoded)
    # Print the one-hot encoded tensor
    print("One-hot Encoded Tensor:")
    print(one_hot_encoded_value)

Index of Maximum Value: 4
One-hot Encoded Tensor:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
