# Task1
 Write a Python program that multiplies a TensorFlow tensor by a scalar value and prints the result.

In [19]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
tensor = tf.constant([22,12,32],dtype=tf.float32)
scalar = 3
result = tensor * scalar
sess = tf.compat.v1.Session()
print(sess.run(result))
sess.close()

[66. 36. 96.]


# TASK 2
Write a Python program that uses TensorFlow to compute the dot product of two vectors (1-D tensors).

In [21]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
vector1 = tf.constant([1, 3, 5], dtype=tf.float32)
vector2 = tf.constant([2, 4, 6], dtype=tf.float32)
dot_product = tf.tensordot(vector1, vector2, axes=1)
sess = tf.compat.v1.Session()
print(sess.run(dot_product))
sess.close()

44.0


# Task3
Write a TensorFlow program that creates two matrices, matrix1 and matrix2, with the following values:
matrix1 = [[1, 2],[3, 4]]
matrix2 = [[5, 6],[7, 8]]
Perform the athematic operations on these matric

In [27]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
matrix1 = tf.constant([[1,2],[3,4]], dtype=tf.float32)
matrix2 = tf.constant([[5,6],[7,8]], dtype=tf.float32)
matrix_sum = tf.add(matrix1,matrix2)
matrix_sub = tf.subtract(matrix1,matrix2)
matrix_mul = tf.matmul(matrix1,matrix2)
with tf.compat.v1.Session() as sess:
    sum_result = sess.run(matrix_sum)
    sub_result = sess.run(matrix_sub)    
    mul_result = sess.run(matrix_mul)    
    print("Matrix Sum:")
    print(sum_result)
    print("\nMatrix Difference:")
    print(sub_result)
    print("\nMatrix Product:")
    print(mul_result)

Matrix Sum:
[[ 6.  8.]
 [10. 12.]]

Matrix Difference:
[[-4. -4.]
 [-4. -4.]]

Matrix Product:
[[19. 22.]
 [43. 50.]]
